// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpzfngaptoybkwkgcasg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwemZuZ2FwdG95Ymt3a2djYXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODg1NTcsImV4cCI6MjA3NDA2NDU1N30.kPWMiUASBLyNeEJlXuJFCNLlouNMuL2JqQWUcs61X_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});